### ISSUE TITLE
Add basic auth to dashboard

### ISSUE THREAD

**Issue by elfenars** [elfenars/ruby-discord-bot#11]
- [x] Add basic auth (for now) to `/dashboard`

**Comment by breakfast1** [comment]
There is all we need [here](http://sinatrarb.com/faq.html). Can I do that ?

**Comment by elfenars** [comment]
Yes, for now only the dashboard URL should be protected.

**Comment by breakfast1** [comment]
Okay fine.

**Comment by elfenars** [comment]
I added you as collaborator. Also, I'm in discord if you wanna discuss more.

**Comment by breakfast1** [comment]
Do we load credentials from env ? See [branch comparison](https://github.com/elfenars/ruby-discord-bot/compare/master...basic-http-auth?expand=1).
