### ISSUE TITLE
Inherit other web modules from Web::Base

### ISSUE THREAD

**Issue by elfenars** [elfenars/ruby-discord-bot#16]
For some reason I get a `stack level too deep` when I create an inheritance to the `Web::Base` in the other modules of the web app. I think it's related to the `require_all` gem or some circular dependency between classes. 

For the moment all the modules are a separate instance of `Sinatra::Base` and then included in the `Web::Base` class. Direct iInheritance would be much better for obvious reasons.

**Comment by breakfast1** [comment]
The same happens without `require_all`. So it is definitely an issue with some circular dependency.

**Comment by elfenars** [comment]
Yeah, I'm too lazy to debug it for now. It's also non critical, I'll take a look after we finish 1.0
