### ISSUE TITLE
Add config interface via web.

### ISSUE THREAD

**Issue by elfenars** [elfenars/ruby-discord-bot#4]
Add a simple interface via web to change things like the bot game, prefix, name, etc.

**Comment by breakfast1** [comment]
It should only be able to changes values in [environment.rb](https://github.com/elfenars/ruby-discord-bot/blob/master/config/environment.rb) ? Or is it possible to change `$bot` on the fly ? I'm not familiar with Discordrb. Should the interface be password protected ? Another issue should be opened on the matter of adding ssl support concerning the whole Sinatra.)

I think I can manage to make a little something.

**Comment by breakfast1** [comment]
Okay. Making the web interface is easy. But if I'm going to do it I'll have to know how to reload data. I assume setting the token and the client id should require complete bot reconnection. But I can reload the bot prefix on the fly right ?

**Comment by elfenars** [comment]
Uhm, I don't think you need to reload the $bot variable at any point really, because the instance of the $bot just contains the Discorb instance.

If what you mean is that you wanna re-instantiate the bot with other token and client then ruby allows ovewriting global variables, so I don't think it would be an issue to re-instantiate it and overwriting the previos instance in the same variable.

All things regarding the web interface should be under the sinatra/ folder btw, ideally context separated, so if you're planning on making a dashboard then a folder for assets, views and other things would be needed.

**Comment by breakfast1** [comment]
Okay. For consistency I'll start by updating configatron entries and then I'll erase $bot with a new instance. Is there a method for safely disconnecting the bot ?

**Comment by breakfast1** [comment]
I finished the web interface pretty straight forwardly. And it updates the configatron entries. But then we'll have to agree on how to reload the bot.

```ruby
$bot.stop
require_rel '../lib/discord.rb'
```

It is ugly but that's all I've found for now.

**Comment by elfenars** [comment]
Do a PR so I can check the code.

**Comment by breakfast1** [comment]
I modified the code so that both web hooks app and web interface can run at the same time. (It didn't with my conf.) Should I commit that ?

**Comment by elfenars** [comment]
I'm fixing that as well, check my next push to master when it happens.

**Comment by elfenars** [comment]
I kept your idea, I just adjusted it a little bit so it's no so bulky.

You could also add some more fields there, like the bot name and the game it's playing.
Let me know if you're interested in future development, I could add you as a contributor if you're interested.

Thanks a lot!

**Comment by breakfast1** [comment]
I'm interested. I was waiting for an opportunity to practice on a project that is not mine.
