### ISSUE TITLE
CSS Framework for web dashboard

### ISSUE THREAD

**Issue by elfenars** [elfenars/ruby-discord-bot#9]
- [ ] Switch to bootstrap/foundation/etc. (Preferably bootstrap)
- [ ] Add feedback messages after config edit (i.e: "Config updated!")

**Comment by breakfast1** [comment]
I finished that. Could you detail the use of `layout_options` ? I can't seem to find any explanation about what it is used for. I first guessed that it holds the path to layouts but it apparently doesn't work that way.
